name: build haskell

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v23

      - name: Set up environment variables
        run: |
          echo "GHC_CHARENC=GHC_NO_UNICODE" >> $GITHUB_ENV
          echo "LANG=en_US.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV

      - name: Enter nix develop shell and build
        run: nix develop --command bash -c "cabal clean && cabal update && cabal build"
